# Shem Configuration File
# This file configures your declarative schema management

# Database connection URL
database_url = "postgresql://postgres:postgres@localhost:5432/myapp_dev"

# Directory paths
schema_dir = "schema"
migrations_dir = "migrations"

[declarative]
enabled = true
# Schema files to include (supports glob patterns)
schema_paths = ["./schema/*.sql"]
# Port for shadow database (used for safe schema diffing)
shadow_port = 5433
auto_cleanup = true

[declarative.safety_checks]
# Warn about potentially destructive operations
warn_on_drop = true
# Require confirmation for destructive operations
require_confirmation = true
# Create backup before applying migrations
backup_before_apply = false

[postgres]
# Schemas to include in search path
search_path = ["public"]
# Extensions to include
extensions = []
# Tables to exclude from schema operations
exclude_tables = []
# Schemas to exclude from schema operations
exclude_schemas = ["information_schema", "pg_catalog"]
